# Generated by Django 5.0.3 on 2024-04-02 12:23

import django.db.models.deletion
from django.db import migrations, models

"""
Migration file for initializing database schema.
"""
class Migration(migrations.Migration):
    """
    Initial migration class for creating database schema.

    This migration initializes the database schema with the following operations:
    - Creation of the 'Categorie' model with fields 'id' and 'nom_categorie'.
    - Creation of the 'Question' model with fields 'id', 'titre', and 'categorie'.
    - Creation of the 'Option' model with fields 'id', 'texte_option', 'valeur_carbone', and 'question'.
    """
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='greenimpact.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte_option', models.CharField(max_length=15)),
                ('valeur_carbone', models.FloatField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponse', to='greenimpact.question')),
            ],
        ),
    ]
